### ISSUE TITLE
Native Miden VM `felt` and `word` support (tracking)

### ISSUE THREAD

**Issue by greenhat** [0xPolygonMiden/compiler#118]
```[tasklist]
### Tasks
- [ ] https://github.com/0xPolygonMiden/compiler/issues/116
- [ ] https://github.com/0xPolygonMiden/compiler/issues/117
- [ ] https://github.com/0xPolygonMiden/compiler/issues/144
```

**Comment by greenhat** [comment]
@bitwalker @bobbinth While working on #138 and modeling `Felt` as `Felt(f64)`, I found a problem, to which I cannot find a solution. Since we treat arithmetic f64 ops as felt ops in Wasm to IR translation, I'd like to ensure that only our SDK code is allowed to use f64 type in Rust code. So far I did not find any way to do it. Otherwise, we can end up with a situation where either a user's code or even worse, a dependency uses f64, and it will be silently translated to felt ops. These errors will be extremely hard to debug.

I wonder if we should reconsider using f64 for felt. My backup plan is to use `Felt(u64)` and define all arithmetic ops as extern functions that end up as Wasm imports that will be translated to felt ops. With this approach, we can dim f64 type illegal on Wasm to IR translation and display a proper user error.

It should look like:

```rust
#[repr(transparent)]
pub struct Felt(u64);
 
extern "C" {
    #[link_name = "miden_compiler_intrinsics_felt_add"]
    fn felt_add(a: Felt, b: Felt) -> Felt;
}

impl Add for Felt {
    type Output = Self;

    #[inline(always)]
    fn add(self, other: Self) -> Self {
        unsafe { felt_add(self, other) }
    }
}
```

**Comment by greenhat** [comment]
Following up our call. Use `Felt(f64)` but with intrinsics (extern functions) as ops and not allow any native float point operations in the translated Wasm code.
