### ISSUE TITLE
Packaging Support

### ISSUE THREAD

**Issue by bitwalker** [0xPolygonMiden/compiler#121]
This is a tracking issue for adding support to the compiler for emitting Miden packages as one of its supported output options. Currently, this consists of the following tasks:

```[tasklist]
### Tasks
- [x] Propose and finalize a specification for the package format
- [x] Identify required vs optional package contents
- [x] Implement core packaging functionality as a separate library (reading metadata/manifest, packing/unpacking/repacking)
- [x] Add support for emitting minimum viable package from backend for libraries/programs
- [x] Add support for consuming packages in the frontend for the purpose of dependency management
```

**Comment by greenhat** [comment]
I'll happily take care of the last task (consuming packages in the frontend).
