### ISSUE TITLE
Wasm table support and `call_indirect` op translation

### ISSUE THREAD

**Issue by greenhat** [0xPolygonMiden/compiler#133]
```[tasklist]
### Tasks
- [ ] Translate Wasm module tables;
- [ ] Translate module table imports/exports and table initialization;
- [ ] Translate Wasm `call_indirect` op;
```
See the semantic details in https://github.com/0xPolygonMiden/compiler/issues/32#issuecomment-1970655897
