### ISSUE TITLE
Implement parser for the IR text format

### ISSUE THREAD

**Issue by bitwalker** [0xPolygonMiden/compiler#14]
For use in testing, it's valuable to have a parser for the IR text format which we currently pretty-print for use in review/diagnosing issues.

- Should build on `miden-diagnostics` and `miden-parsing`
- Should use `lalrpop` for the parser
- May use a dedicated AST structure for easier integration with the parser, but ideally should parse directly to the IR, since a standalone AST has no use on its own, and it should be feasible to parse in to the IR data structure anyway.
- It's fine to update the pretty-printed format itself to ensure we have all the data needed to reconstruct the IR in-memory, it should be fairly complete at this point, but it may be necessary to enrich the format further to preserve more metadata.
```[tasklist]
### Tasks
- [x] Define AST that corresponds to the IR syntax, reusing IR types where possible
- [x] Implement LALRPOP grammar that parses the IR text format into the above AST
- [x] Implement a translation pass that converts the AST structure to the actual IR
- [x] Define a test that roundtrips a basic function, like fib, to ensure that a IR-defined function, when printed to text form, parsed back to IR, and printed again, produces the same output
```

Some implementation notes/recommendations:

You can refer to the [AirScript parser crate] to get a feel for how to define a LALRPOP grammar, and use it to construct the AST along with diagnostics, source spans, etc. I wouldn't focus too much on mimicking it's specific implementation, since it's use case is different, but it should provide some useful guidance/hints on how to approach certain problems. The grammar, as the name implies, drives a LR(1)/LALR parser generator, so it can be occasionally tricky to handle certain semi-ambiguous parts of a language. The IR syntax is pretty explicit though, and doesn't have a lot of fancy expression handling and the like, so that shouldn't be an issue. Let me know if you hit any shift/reduce errors though.

For translating the AST to the IR, I would implement it as a `Pass`, using a simple recursive traversal, basically the following:

```rust
use std::collections::VecDeque;
use miden_diagnostics::DiagnosticsHandler;
use miden_hir_pass::Pass;
use smallvec::SmallVec;
use rustc_hash::{FxHashMap, FxHashSet};

use crate::{self as hir, ast, ModuleBuilder, ModuleFunctionBuilder};

pub struct AstToIr<'a> {
    /// Used for emitting diagnostics
    diagnostics: &'a DiagnosticsHandler,
    /// Used to map block identifiers parsed into the AST, to their corresponding identifiers in the IR
    block_map: FxHashMap<ast::BlockId, hir::Block>,
    /// Used to map value identifiers parsed into the AST, to their corresponding identifiers in the IR
    value_map: FxHashMap<ast::ValueId, hir::Value>,
}
impl<'a> AstToIr<'a> {
    pub fn new(diagnostics: &'a DiagnosticsHandler) -> Self {
        Self {
            diagnostics,
            block_map: Default::default(),
            value_map: Default::default()
        }
    }
}
impl<'p> Pass for AstToIr<'p> {
    type Input<'a> = ast::Module;
    type Output<'a> = Box<hir::Module>;
    type Error = anyhow::Error;

    fn run<'a>(&mut self, mut module: Self::Input<'a>) -> Result<Self::Output<'a>, Self::Error> {
       let mut builder = ModuleBuilder::new(module.name);
       builder.with_span(module.span());

       for global in module.globals.into_iter() {
           // Here I'm assuming the AST uses our Type and Linkage types
           let gv = builder.declare_global_variable(global.name, global.ty, global.linkage, global.span())?;
           // Globals don't necessarily have an initializer
           if let Some(init) = global.initializer {
              builder.set_global_initializer(gv, init);
           }
       }

       for function in module.functions.into_iter() {
           // Here I'm assuming the AST uses our Signature type
           let mut fb = builder.build_function(function.name, function.signature, function.span())?;
           self.translate_function(&mut fb)?;
       }

       Ok(builder.build())
    }
}
impl<'a> AstToIr<'a> {
    fn translate_function(&mut self, builder: &mut ModuleFunctionBuilder, function: ast::Function) -> anyhow::Result<()> {
       // We need to visit all blocks to create the corresponding IR block before we do the translation
       for (i, block) in function.blocks.iter().enumerate() {
           // Here I'm assuming the first block in the AST is always the entry block, which should be true.
           let block_id = if i == 0 {
               let id = builder.entry_block();
               // The entry block is already populated with parameters based on the function signature,
               // we just need to map the identifiers in the AST to their IR equivalents
               let values = builder.data_flow_graph().block_params(id);
               assert_eq!(values.len(), block.params.len());
               for (param, value) in block.params.iter().zip(values.iter()) {
                   self.value_map.insert(param.id, value);
               }
               id
           } else {
               let id = builder.create_block();
               // For all other blocks, we need to alter the block parameter list
               for param in block.params.iter() {
                   // Here I'm assuming we're using our Type enum in the AST
                   let value = builder.append_block_param(id, param.ty.clone(), param.span());
                   self.value_map.insert(param.id, value);
               }
               id
           };
           // Make sure we map the block id in the AST to the IR block
           self.block_map.insert(block.id, block_id);
       }

       // Translate the body of the function by walking the control flow graph,
       // i.e. we translate the entry block, then follow control flow instructions
       // to the next unvisited block, and so on, until all blocks are visited. We
       // discard unvisited blocks, as those are by definition dead code.
       let mut visited = FxHashSet::<ast::BlockId>::default();
       let mut worklist = VecDeque::<ast::BlockId>::default();
       worklist.push_back(function.blocks[0].id);

       while let Some(ast_block) = worklist.pop_front() {
           if !visited.insert(ast_block) {
               continue;
           }
           self.translate_block(builder, &function.blocks[ast_block], &mut worklist)?;
       }

       // We're done
       builder.build(self.diagnostics).map(|_| ())
    }

    fn translate_block(&mut self, builder: &mut ModuleFunctionBuilder, block: &ast::Block, worklist: &mut VecDeque<ast::BlockId>) -> anyhow::Result<()> {
       let block_id = self.block_map[block.id];
       builder.switch_to_block(block_id);

       for op in block.ops.iter() {
           let span = op.span();
           match op {
               // This is an example of how to handle control flow instructions
               ast::Instruction::Br(ast::Br { dest, args, .. }) => {
                   // Make sure we visit the destination block next
                   worklist.push_back(*dest);
                   // Map the instruction data
                   let dest = self.block_map[dest];
                   let args = args.iter().map(|arg| self.value_map[arg]).collect::<SmallVec<[hir::Value; 2]>>();
                   builder.ins().br(dest, &args, span);
               }
               // This is an example of how to handle instructions with results
               ast::Instruction::Add(ast::Add { lhs, rhs, output, .. }) => {
                   // We're able to assume that values are already defined because our traversal enforces
                   // that we visit predecessors of this instruction before the instruction itself.
                   let lhs = self.value_map[lhs];
                   let rhs = self.value_map[rhs];
                   let result = builder.ins().add(lhs, rhs, span);
                   self.value_map.insert(*output, result);
               }
               _ => unimplemented!(),
           }
       }

       Ok(())
    }
}
```

That's the broad strokes, but obviously a lot of details are left out. If you have any questions, or find any issues with the above approach, let me know and we can discuss alternatives.

**Comment by bitwalker** [comment]
@jjcnn I've updated this issue with some more detail to give you a better idea of what I'm looking for with the parser, and how I'd break it down in terms of PRs. If you have any additional questions, or hit any snags, let me know and we can discuss further.

**Comment by jjcnn** [comment]
BTW, we don't have any way to represent a notion of modules or libraries at the IR level, right? I couldn't find any.

**Comment by bitwalker** [comment]
> BTW, we don't have any way to represent a notion of modules or libraries at the IR level, right? I couldn't find any.

Well, that's what `Program` and `Module` essentially are. `Module` is a single module, and `Program` is one or more `Module` grouped together either as a library or "executable" (i.e. "program" in Miden parlance). As far as how that affects the parser though, the only thing we meaningfully represent in the textual IR are individual modules and relationships between them. A module references other modules implicitly via externally-defined functions, i.e. function declarations without a body, whose identifier is a fully-qualified name. For example, `std::math::u64::unchecked_add` is a valid function name for an external definition, and implicitly forms a dependency on the `std::math::u64` module.

> ident ::= string // Q: I'm guessing this is the typical alphanum plus special chars, and must start with a letter or an underscore?

There are really five different types of identifiers:

1. Modules and functions, these should follow the same rules as imposed by Miden Assembly, as we don't actually have any requirements ourselves, but we do want to make sure we aren't generating invalid Miden Assembly by being too open with naming conventions.
2. Global variables, these can use essentially any combination of alphanumeric or the following special characters: `$`, `.`, `_`, `-`, `@`. These don't ever end up in MASM, and the names are generally those produced by Rust/LLVM for global symbols meant to be processed by the linker.
3. Entity identifiers; i.e. generated identifiers used for IR entities such as blocks, values, etc. These will always be one or more lower-case alpha characters, followed by one or more numeric characters, e.g. `v123` or `blk0`.
4. Type names; the set of these is closed, so they could be treated as keywords, but they come in one of two forms, either entirely lower-case alphanumeric (always with a leading alpha character), or a special type, e.g. `()` for the unit type.
5. Instruction names; again the set of these is closed, but they are universally always lower-case alphanumeric (with a leading alpha), optionally namespaced/typed using `.` as the namespace/type separator. For example, `const.i1` is a typed constant operation, while `assert.eq` is a namespaced assertion operation.

That's probably going further than you were asking, but I wanted to lay out the different identifier types I'm aware of just from writing the formatter. How one chooses to represent them in the grammar is a different thing (i.e. you might make type/instruction names keywords rather than open identifiers, since it's probably easier that way).

> // Q: I'm ignoring Unknown ('?') and Never ('!') here - presumably those are only for internal use?

You shouldn't ever see `?` in valid IR, it's more for debugging purposes when something is untyped. The never type could appear in valid IR, semantically it would be equivalent to calling a function which never returns (i.e. a function which raises an exception, or always traps). I don't think we're likely to see that anytime soon though, so you can feel free to punt on that for now if you like.

> // Q: Do we allow empty structs? The Type enum does.

Yes, they are basically used to represent zero-sized types, e.g. Rust's `PhantomData` type.

> // Q: Should we use "true" and "false" instead of "const.i1 1" and "const.i1 0"?

I'd be fine with `const.i1 true` and `const.i1 false`, to make the meaning a bit clearer, but I want to keep the `results = opcode ..args` format of the IR, so I wouldn't want to elide the `const.i1` opcode name just to special case boolean values.

> // Q: What happens here? Do values always have to have the format "v42"?

Yeah basically, the precise regex would be `v(0|[1-9][0-9]+)`, i.e. the integer part never has leading zeroes, but `v0` is a valid identifier. The same is true of blocks with the different being the prefix, which is `blk`; global variables, which use `gvar`, and global values, which use `gv`.

> // Q: What happens here? Do values always have to have the format "block42"?

Answered above, but yes.

> switch_branches ::= , value => label // Q: Block arguments don't seem to be written by the formatter
>  | , label // Q: Again, block arguments seem to be missing

We don't allow branching with arguments via `switch` currently.

> // Q: None of the numerical ops print information about their overflow behavior, but overflow behavior needs to be part of the grammar, no?

Good point, the formatter was written before we introduced support for changing the overflow behavior, and looks like we never added that. You can assume that this will use `.<overflow>` syntax attached to the opcode, e.g. `add.checked`. In essence, the overflow behavior is a distinct variant of the instruction, so we treat it as part of the opcode.

> store // Q: Not printed by the formatter

It is, it's just not apparent how - the builders create `store` using the `BinaryOp` instruction type currently. I need to change that to use `PrimOp` though. In any case, both instruction types are formatted currently.

> alloca // Q: Not printed by the formatter

It is, as a primop.

> // Q: "unreachable" is considered a primary op. I figure we don't need it in the syntax.

We definitely want to represent it as an explicit instruction, that's after all why we allocated an opcode for it. Without syntax, I'm not sure how we'd know that a block is terminated with unreachable code when parsing the IR. In any case, you should assume that if we have an opcode, it will be printed as an instruction, and we'll need to parse it back as such.

NOTE: I should have documented this somewhere, since nomenclature like this is necessarily ambiguous at times, but "primop" here is shorthand for "primitive operation", i.e. a core runtime function that has special compiler support. In our case, primops are things which aren't translated into Miden Assembly directly, or which are implemented using sequences of instructions in MASM, and don't have dedicated instructions in MASM. This isn't a hard and fast rule, because signed arithmetic ops for example aren't going to be represented as primops, they'll be unary/binary ops just like the unsigned versions - so it might be more intuitive to say that primops are "special" ops, i.e. things that don't fit into any better category.

> syscall // Q: This one is missing from write_operands. Is that deliberate?

It's not, `call` and `syscall` are two different opcodes represented by the `Call` instruction type, the way their operands are formatted is identical, only the opcode is different. If you look at `write_instruction`, you'll see that we separate out writing the opcode and the operands.

> // Q: There's a second output format for branch operations in the write_operands function (line 189), but I don't see how that format can ever be reached.

I'm not actually sure why there are two cases there, I think that might be a leftover of the original set of branch instructions I envisioned, but that was rewritten, and I guess I never removed that clause. In any case, we want to keep the first one, but remove the `if *op == Opcode::Br`, and remove the second one. You can do that in your PR if you like, or I can do it whenever I'm in there next.

// Q: No legal opcode exists for primop_imm, so ignoring that instruction

Well, any primop opcode that can support an immediate argument, could use the `PrimOpImm` instruction type, but I think you are right that we currently do not construct any via the builders today.

// Q: No builder exists for MemGrow ("memory.grow") - not sure if we want this in the syntax

You can punt on this one, we can add it later easily enough.

---

Hope that is helpful! Let me know if you have any further questions, or if you'd like me to elaborate more on anything I said above.

**Comment by jjcnn** [comment]
Updated grammar based on the above comments, and with programs and modules added.

I'm not 100% certain that the global variable declarations are correct, but they must be quite close.

```
number ::= // signed integer

unsigned_nonzero_number ::= // unsigned nonzero integer. It's not a problem to allow zeros, but unsigned is required.

constant ::= // hex string

ident ::= string // See discussion of allowable identifiers above

type ::= ()   // Ignoring Unknown ('?')
       | !    // Never
       | i1
       | i8
       | u8
       | i16
       | u16
       | i32
       | u32
       | i64
       | u64
       | i128
       | u128
       | u256
       | isize
       | usize
       | f64
       | felt
       | *mut type  // Ptr
       | &mut type  // NativePtr
       | { types? }
       | [ type ; number ]

more_types ::= , type

types ::= type more_types*

immediate_type ::= const.i1
                 | const.i8
                 | const.i16
                 | const.i32
                 | const.i64
                 | const.isize
                 | const.felt
                 | const.f64

immediate ::= immediate_type number   // TODO: introduce "const.i1 true" and "const.i1 false"

immediates ::= immediate more_immediates*

more_immediates ::= , immediate

value ::= v(0|[1-9][0-9]+)

values ::= value more_values*

more_values ::= , value



external_function ::= signature ;

call_convention ::= cc(fast)
                  | cc(kernel)

function_ident ::= ident
                 | ident::ident

param_purpose ::=                     // default
                | sret

param_extension ::=                   // none
                  | zext
                  | sext

param ::= param_purpose param_extension type

more_params ::= , param

function_params ::= param more_params*

return ::= param_extension type

more_returns ::= , return

function_return ::= -> return more_returns*

signature ::= pub? call_convention? fn function_ident (function_params?) function_return?

function ::= signature {{ block* }}




label ::= blk(0|[1-9][0-9]+)

block_arg ::= value : type

more_block_args ::= , block_arg

block_args ::= block_arg more_block_args*

block_header ::= label (block_args) :
               | label : 

block ::= block_header instruction*



instruction ::= values = operation : types
              | operation

destination ::= label (block_args)
              | label

switch_branches ::= , value => label
                  | , label

offset ::= +unsigned_nonzero_number   // Must be i32, but with an explicit + for positive numbers
         | -unsigned_nonzero_number

overflow ::= .unchecked
           | .checked
           | .wrapping
           | .overflowing

binaryop ::= add overflow
           | sub overflow
           | mul overflow
           | div overflow
           | min overflow
           | max overflow
           | mod overflow
           | divmod overflow
           | exp overflow
           | and
           | band overflow
           | or
           | bor overflow
           | xor
           | bxor overflow
           | shl overflow
           | shr overflow
           | rotl overflow
           | rotr overflow
           | neg
           | eq
           | neq
           | gt
           | gte
           | lt
           | lte
           | store // Q: Not printed by the formatter

binaryop_imm ::= add_imm overflow
               | sub_imm overflow
               | mul_imm overflow
               | div_imm overflow
               | min_imm overflow
               | max_imm overflow
               | mod_imm overflow
               | divmod_imm overflow
               | exp_imm overflow
               | and_imm
               | band_imm overflow
               | or_imm
               | bor_imm overflow
               | xor_imm
               | bxor_imm overflow
               | shl_imm overflow
               | shr_imm overflow
               | rotl_imm overflow
               | rotr_imm overflow
               | neg_imm

unaryop ::= inv
          | incr
          | pow2
          | not
          | bnot
          | popcnt
          | is_odd
          | cast
          | ptrtoint
          | inttoptr
          | truncw
          | zext
          | sext

unaryop_imm ::= const.i1
              | const.i8
              | const.i16
              | const.i32
              | const.i64
              | const.isize
              | const.felt
              | const.f64
              
primop ::= select
         | assert
         | assertz
         | assert.eq
         | alloca
         | unreachable

callop ::= call
         | syscall

operation ::= binaryop value value
            | binaryop_imm value immediate
            | unaryop value
            | unaryop_imm immediate
            | ret values?
            | callop function_ident (values?)
            | cond value, destination, destination
            | branch destination
            | switch value switch_branches
            | test . type value
            | primop values?
            // Ignoring primop_imm, since no legal opcode exists for it
            | load value
            | memcpy . type value, value, value
            // TODO: | inlineasm "asm_instruction*", values?     Ignored for now
            | globalvalueop
            // TODO: MemGrow ("memory.grow") - ignored for now


globalvalue_nested ::= @ ident offset?
                     | * globalvalue_nested // Load
                     | * (globalvalue_nested) offset // Load with offset
                     | * (globalvalue_nested) offset? as global_type // Cast

globalvalueop ::= | global.symbol @ ident offset?  // Symbol
                  | global.load globalvalue_nested // Load
                  | global.load (globalvalue_nested) offset // Load with offset
                  | global.load (globalvalue_nested) offset? as type // Cast
                  | global.iadd.number.type globalvalue_nested //IAddImm




module_type ::= kernel
              | module

module ::= module_type ident function* external_function*


linkage ::= internal
          | odr
          | external

globalvar_initializer ::= = constant

globalvar ::= ident type linkage globalvar_initializer?


program ::= module* function_ident? globalvar*
```

**Comment by bitwalker** [comment]
Implemented and merged via #48
