### ISSUE TITLE
Test suite for Miden SDK (`tx_kernel` API) ABI transformation

### ISSUE THREAD

**Issue by greenhat** [0xPolygonMiden/compiler#160]
### Goal

The goal is to test both the ABI transformation strategies implemented in the [frontend](https://github.com/0xPolygonMiden/compiler/blob/6466b64e0434d1a77e4379e3035a5aaa9bd4c356/frontend-wasm/src/miden_abi/transform.rs#L48-L113) and the Rust bindings written for every Miden SDK `tx-kernel` API function in the `miden-tx-kernel` crate (see [`get_inputs`](https://github.com/0xPolygonMiden/compiler/blob/6466b64e0434d1a77e4379e3035a5aaa9bd4c356/sdk/tx-kernel/src/lib.rs#L41-L61) for example). 

### Implementation details

We can generate the `tx_kernel` API function stubs in the IR that will assert certain facts about the inputs and return mocked data, and then run the compiled code in the Miden VM. This approach has a drawback that it would not be able to use property-based testing, since the inputs and outputs are hard-coded in the stubs.
```[tasklist]
### Tasks
- [x] MASM compilation is passing
- [ ] https://github.com/0xPolygonMiden/compiler/issues/223
- [x] MASM assembly is passing
- [x] Generate Rust code to test the values received from the `tx_kernel::get_inputs` call
- [ ] https://github.com/0xPolygonMiden/compiler/issues/225
- [ ] https://github.com/0xPolygonMiden/compiler/issues/230
```

**Comment by bitwalker** [comment]
Closed via #284
