### ISSUE TITLE
Tests for `intrinsics::mem::store_sw/load_sw`

### ISSUE THREAD

**Issue by greenhat** [0xPolygonMiden/compiler#234]
Use IR's `store` and `load` calls for i32 type values under proptest and cover the pattern used by rustc of using Wasm `i32.load/store` ops. We want to also test `OpEmmiter::emit_native_ptr` (raw<->native ptr translation) as part of these tests.
```[tasklist]
### Tasks
- [x] failing assert in `replace_element`;
- [x] returns 0 in some cases (seems like when ptr % 4 == 0);
- [x] out of bounds memory access on some ptrs;
```
