### ISSUE TITLE
Test release process by publishing compiler and Miden SDK crates

### ISSUE THREAD

**Issue by greenhat** [0xPolygonMiden/compiler#246]
```[tasklist]
### Tasks (according to CONTRIBUTING.md)
- [x] Run `release-plz update` in the repo root folder to update the compiler crates versions and generate changelogs.
- [x] Run `release-plz update` in the `sdk` folder to update the SDK crates versions and generate changelogs.
- [x] Create a release PR naming the branch with the `release-plz-` suffix (its important to use this suffix to trigger the crate publishing on CI in step 4).
- [x] Review the changes in the release PR, commit edits if needed and merge it into the main branch.
- [x] The CI will automatically run `release-plz release` after the release PR is merged to publish the new versions to crates.io.
```

**Comment by greenhat** [comment]
@bitwalker Well, the first attempt to publish https://github.com/0xPolygonMiden/compiler/pull/249#pullrequestreview-2186336971 is failed:
```
error: failed to publish to registry at https://crates.io/
    
    Caused by:
      the remote server responded with an error (status 400 Bad Request): The following category slugs are not currently supported on crates.io: Compilers
    
      See https://crates.io/category_slugs for a list of supported slugs.
```

I've run the `--dry-run` (I should've done it earlier 🤦)  and besides that, we're going to need to specify the `version` along the `path` for all the deps:
```
  2024-07-19T13:34:37.502097Z ERROR  failed to release package

Caused by:
    failed to publish midenc-session:     Updating crates.io index
    error: all dependencies must have a version specified when publishing.
    dependency `midenc-hir-symbol` does not specify a version
    Note: The published dependency will use the version from crates.io,
    the `path` specification will be removed from the dependency declaration.
```

I'm making a new release PR with these fixes.

**Comment by greenhat** [comment]
The latest publishing attempt - https://github.com/0xPolygonMiden/compiler/actions/runs/10043779504/job/27757299114
Issues:
- `miden-assembly` does not have `version` set;
- git tags are pushed despite the `git_tag_enable=false` in the `release-plz.toml`.

**Comment by greenhat** [comment]
We cannot set the `version` for VM crates in our deps since we depend on the unreleased version of the VM (v.0.10.0) on the following features in particular:
- https://github.com/0xPolygonMiden/miden-vm/pull/1363
- https://github.com/0xPolygonMiden/miden-vm/pull/1360

Which, in turn, depends on the assembler refactoring https://github.com/0xPolygonMiden/miden-vm/pull/1277, so backporting probably is not an option.

@bobbinth Do we have any ETA for the VM v.0.10.0 release? It seems that we can release only after the VM v.0.10.0 release.

**Comment by bitwalker** [comment]
@greenhat As far as I'm aware, if `0.10.0` is the version in the VM crates `Cargo.toml`, we can absolutely use that as the version in our `Cargo.toml` if we're using a `git` dependency, since that's what the version must match, not what is currently published to crates.io - at least as far as I understand the Cargo resolver.

Does it actually raise an error if you try to depend on a crate in a git repo which hasn't been published to crates.io? That doesn't seem right.

**Comment by greenhat** [comment]
> @greenhat As far as I'm aware, if `0.10.0` is the version in the VM crates `Cargo.toml`, we can absolutely use that as the version in our `Cargo.toml` if we're using a `git` dependency, since that's what the version must match, not what is currently published to crates.io - at least as far as I understand the Cargo resolver.

Yes, it should work when you are building locally. However, publishing to crates.io will use the registry version. In our case, it'd be `0.10.0`, which has not yet been published on crates.io. See https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations :

It is possible to specify both a registry version and a git or path location. The git or path dependency will be used locally (in which case the version is checked against the local copy), and when published to a registry like crates.io, it will use the registry version. Other combinations are not allowed.

 
> Does it actually raise an error if you try to depend on a crate in a git repo which hasn't been published to crates.io? That doesn't seem right.

I haven't tried it yet because version `0.9.1`(published) is set in the VM crates in the `next` branch of the VM repo. We can try to set it to `0.10.0` version in VM crates and try to publish our crates. From my experience and the Cargo book excerpt above it should raise an error.

**Comment by bobbinth** [comment]
> @bobbinth Do we have any ETA for the VM v.0.10.0 release?

We'll publish v0.10 as soon as MAST refactoring of the assembler is done. There are probably 3 - 4 PRs let on this though - so, maybe some time closer to the end of next week.

If we do publish compiler crates using git dependencies, we should make sure to reference a specific commit rather than the `next` branch as I'm anticipating some breaking changes in the assembler between now and v0.10 release.

**Comment by greenhat** [comment]
> > @bobbinth Do we have any ETA for the VM v.0.10.0 release?
> 
> We'll publish v0.10 as soon as MAST refactoring of the assembler is done. There are probably 3 - 4 PRs let on this though - so, maybe some time closer to the end of next week.
> 
> If we do publish compiler crates using git dependencies, we should make sure to reference a specific commit rather than the `next` branch as I'm anticipating some breaking changes in the assembler between now and v0.10 release.

I don't think git dependency will work for a published crate. Do you mind if I make a PR to the VM repo and set the version of VM crates to `0.10.0` to test it? 

We could do a "soft" release while we're waiting for the VM v0.10 release.  By "soft", I mean that instead of installing our extension via 
```
cargo install cargo-miden
```
a user will need to use our repo and run 
```
cargo install --git https://github.com/0xPolygonMiden/compiler cargo-miden
```

**Comment by bobbinth** [comment]
> Do you mind if I make a PR to the VM repo and set the version of VM crates to `0.10.0` to test it?

That would be great!

**Comment by greenhat** [comment]
Confirmed. The last publishing attempt https://github.com/0xPolygonMiden/compiler/actions/runs/10195526684/job/28204408562 failed due to the VM crates for version `0.10.0` are not found on crates.io:
```
  2024-08-01T09:16:58.465701Z ERROR  failed to release package

Caused by:
    failed to publish midenc-hir:     Updating crates.io index
       Packaging midenc-hir v0.0.1 (/home/runner/work/compiler/compiler/hir)
       Verifying midenc-hir v0.0.1 (/home/runner/work/compiler/compiler/hir)
        Updating crates.io index
    error: failed to verify package tarball
    
    Caused by:
      failed to select a version for the requirement `miden-assembly = "^0.10"`
      candidate versions found which didn't match: 0.9.2, 0.9.1, 0.9.0, ...
      location searched: crates.io index
      required by package `midenc-hir v0.0.1 (/home/runner/work/compiler/compiler/target/package/midenc-hir-0.0.1)`
```
I suppose we will publish a release after VM `v0.10.0` is published then.

**Comment by greenhat** [comment]
@bobbinth Could you please create two new crates at crates.io:
- `midenc-runner` new crate for the VM executor;
- `miden-base-sys` new crate for the rollup part of the SDK instead of `miden-tx-kernel-sys` which can be deleted;

Thanks!

**Comment by bitwalker** [comment]
`midenc-runner` was renamed `midenc-debug` FYI

**Comment by bobbinth** [comment]
Both crates ([1](https://crates.io/search?q=midenc-debug), [2](https://crates.io/search?q=miden-base-sys)) are now on crates.io.

**Comment by greenhat** [comment]
@bobbinth Could you please create the new crate at crates.io for `miden-sdk-alloc`? Thanks!

**Comment by bobbinth** [comment]
> @bobbinth Could you please create the new crate at crates.io for `miden-sdk-alloc`? Thanks!

Done! ([here](https://crates.io/crates/miden-sdk-alloc)).

**Comment by greenhat** [comment]
The publishing test completed successfully - https://github.com/0xPolygonMiden/compiler/actions/runs/10611124186/job/29409979512
