### ISSUE TITLE
Binding against Miden procedures from Rust

### ISSUE THREAD

**Issue by bitwalker** [0xPolygonMiden/compiler#304]
Currently, the compiler understands how to generate the necessary glue code for the Miden FFI (foreign-function interface). It does so based on having a type signature and a known calling convention/ABI. However, this is currently restricted to a hardcoded whitelist of known Miden Assembly procedures and their corresponding signatures.

We want to remove this manually-maintained list of procedures, and open up the FFI to any procedure implemented in Miden Assembly. However, in order to do so, we need to be able to obtain the signature/calling convention/ABI from metadata, which currently doesn't exist anywhere.

This is a tracking issue for the implementation of this feature

```[tasklist]
### Tasks
- [ ] #121 
- [ ] 0xPolygonMiden/miden-vm#1434
- [ ] Provide a way to express type signatures, calling convention, and ABI and include them in the procedure metadata in MAST
- [ ] Implement type syntax in Miden Assembly. This would largely correspond to the IR type system, and would allow not only expressing the type signature of a procedure, but the ability to do basic type checking of Miden Assembly code. This would subsume whatever out-of-band mechanism is being used (Optional)
- [ ] Assign an ABI transformation strategy based on the type signature of a procedure, or allow specifying it manually via annotations
- [ ] Extend logic for applying ABI transformations to any `extern` function for which we have type signature information. Since the ABI transformations are type-driven, this will be ignored except in cases where it should be applied.
- [ ] Remove the hardcoded whitelist, once we can obtain the metadata for those procedures programmatically
```
