### ISSUE TITLE
Implement test harness for compiler

### ISSUE THREAD

**Issue by bitwalker** [0xPolygonMiden/compiler#5]
In order to make for a better development experience, and to ensure we have an easy way of doing end-to-end testing, we need a test harness with the following properties:

```[tasklist]
### Tasks
- [x] Can construct an IR function and lower it to Miden Assembly
- [x] Can convert a high-level language with Miden IR support to its corresponding IR representation (see #22)
- [x] Can assert on properties of the generated Miden Assembly
- [x] Support parsing IR from text, running one or more passes, then emitting IR to stdout
- [x] Support parsing IR from text, compiling to MASM, and running with the MASM emulator
```

Some of the tooling for this is already in place, but the actual harness is not implemented yet.

**Comment by bitwalker** [comment]
This is basically done, there is decent support now for writing unit tests (and even some complex integration tests) in the Miden IR crates, though it is quite verbose and hard to read due to all of the boilerplate constructing programs by hand. What remains at this point is dependent on the compiler executable, which is just waiting on #22 to be merged, at which point we'll be able to start writing more readable, in-depth tests that verify the various analysis and transformation passes with a lot less boilerplate.

**Comment by bitwalker** [comment]
This is complete now that #50 is merged. There are still some improvements I'd like to make to our testing infra, but we have the key points done now, and with #49 being fleshed out, we'll be in a good place soon.
