### ISSUE TITLE
Translate parsed Wasm component to IR (tracking)

### ISSUE THREAD

**Issue by greenhat** [0xPolygonMiden/compiler#89]
This is a tracking issue for the Wasm CM translation implementation.

```[tasklist]
### Tasks
- [ ] https://github.com/0xPolygonMiden/compiler/issues/108
- [ ] https://github.com/0xPolygonMiden/compiler/issues/109
- [ ] https://github.com/0xPolygonMiden/compiler/issues/110
```
